openapi: 3.0.1
info:
  title: Spring Boot Redis Swagger
  description: Swagger documentation for application endpoints
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: users
    description: Operations about user
paths:
  /users:
    get:
      tags:
        - users
      summary: Returns all users.
      responses:
        '200':
          description: OK
    post:
      tags:
        - users
      summary: Creates user.
      requestBody:
        description: Create a new user in the repository
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - users
      summary: Deletes all users.
      responses:
        '200':
          description: OK

  /users/{userId}:
    get:
      tags:
        - users
      summary: Find user by id.
      parameters:
        - name: userId
          in: path
          description: ID of user to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    patch:
      tags:
        - users
      summary: Updates user.
      parameters:
        - name: userId
          in: path
          description: ID of user to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: update user in the repository
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: OK
    delete:
      tags:
        - users
      summary: Delete user by id.
      parameters:
        - name: userId
          in: path
          description: ID of user to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK

components:
  schemas:
    user:
      type: object
      properties:
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doh
        email:
          type: string
          example: john@doe.gmail.com
        age:
          type: integer
          format: int64
          example: 34